folio:
  tenant:
    validation:
      enabled: true
server:
  port: 8081
logging:
  level:
    liquibase: debug
spring:
  application:
    name: mod-data-export-spring-migrated
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_DATABASE:okapi_modules}
management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: health