openapi: 3.0.0
info:
  title: Data-export error logs API
  version: v1
servers:
  - url: /data-export/
paths:
  /mapping-profiles:
    description: Service provides APIs supporting Error logs
    get:
      description: Retrieve a list of log items
      operationId: getLogsByFilter
      parameters:
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
        - $ref: "#/components/parameters/trait_queryable_query"
      responses:
        200:
          description: Returns a list of log items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorLogCollection'
              example:
                $ref: '#/components/examples/errorLogCollection'
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            text/plain:
              example: unable to list logs -- malformed parameter 'query', syntax error at column 6
        "401":
          description: Not authorized to perform requested action
          content:
            text/plain:
              example: unable to list logs -- unauthorized
        "422":
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
components:
  schemas:
    recordLog:
      $ref: 'schemas/logs/recordLog.json#/RecordLog'
    errorLog:
      $ref: 'schemas/logs/errorLog.json#/ErrorLog'
    errorLogCollection:
      $ref: 'schemas/logs/errorLogCollection.json#/ErrorLogCollection'
    errors:
      $ref: 'schemas/errors.json'
  examples:
    errorLogCollection:
      value:
        $ref: 'examples/logs/errorLogCollection.json'
  parameters:
    trait_queryable_query:
      name: query
      in: query
      description: A query string to filter rules based on matching criteria in fields.
      schema:
        type: string
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer