openapi: 3.0.0
info:
  title: Data-export mapping profiles API
  version: v1
servers:
  - url: /data-export/
paths:
  /mapping-profiles:
    post:
      description: Create a new mapping-profile item
      operationId: postMappingProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mappingProfile'
            example:
              $ref: '#/components/examples/mappingProfile'
      responses:
        "201":
          description: Returns a newly created item, with server-controlled fields like 'id' populated
          content:
            application/json:
              example:
                $ref: '#/components/examples/mappingProfile'
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            text/plain:
              example: unable to add mapping-profile -- malformed JSON at 13:3
        "401":
          description: Not authorized to perform requested action
          content:
            text/plain:
              example: unable to create mapping-profiles -- unauthorized
        "422":
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
    get:
      description: Retrieve a list of mapping-profile items
      operationId: getMappingProfilesByFilter
      parameters:
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
        - $ref: "#/components/parameters/trait_queryable_query"
      responses:
        "200":
          description: Returns a list of mapping-profile items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mappingProfileCollection'
              example:
                $ref: '#/components/examples/mappingProfileCollection'
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            text/plain:
              example: unable to list mapping-profiles -- malformed parameter 'query', syntax error at column 6
        "401":
          description: Not authorized to perform requested action
          content:
            text/plain:
              example: unable to list mapping-profiles -- unauthorized
        "422":
          description: Validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
  /mapping-profiles/{id}:
    get:
      description: Retrieve mapping-profile item with given id
      operationId: getMappingProfileById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the mapping profile
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Returns mapping profile with a given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mappingProfile'
              example:
                $ref: '#/components/examples/mappingProfile'
        "404":
          description: Mapping profile with a given ID not found
          content:
            text/plain:
              example: mapping-profile not found
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
    delete:
      description: Delete mapping-profile item with given id
      operationId: deleteMappingProfileById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the mapping profile
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "204":
          description: Mapping profile deleted successfully
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            text/plain:
              example: unable to delete mapping-profile -- constraint violation
        "404":
          description: Mapping profile with a given ID not found
          content:
            text/plain:
              example: mapping-profile not found
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
    put:
      description: Update mapping-profile item with given id
      operationId: updateMappingProfileById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the mapping profile
          schema:
            $ref: "#/components/schemas/UUID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mappingProfile'
            example:
              $ref: '#/components/examples/mappingProfile'
      responses:
        "204":
          description: Mapping profile successfully updated
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            text/plain:
              example: unable to update mapping-profile -- malformed JSON at 13:4
        "404":
          description: mapping profile with a given ID not found
          content:
            text/plain:
              example: mapping-profile not found
        "500":
          description: Internal server error
          content:
            text/plain:
              example: Internal server error
components:
  schemas:
    UUID:
      type: string
      format: uuid
    errors:
      $ref: 'schemas/errors.json'
    mappingProfile:
      $ref: 'schemas/profiles/mappingProfile.json'
    mappingProfileCollection:
      $ref: 'schemas/profiles/mappingProfileCollection.json'
  examples:
    mappingProfile:
      value:
        $ref: 'examples/profiles/mappingProfile.sample'
    mappingProfileCollection:
      value:
        $ref: 'examples/profiles/mappingProfileCollection.sample'
  parameters:
    trait_queryable_query:
      name: query
      in: query
      description: A query string to filter rules based on matching criteria in fields.
      schema:
        type: string
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer